In [6]:
import pandas as pd

In [7]:
d=pd.read_csv("Tamil_songs.csv")
d

,song_name,singer,singer_id,duration,language,released_date,danceability,acousticness,energy,liveness,loudness,speechiness,tempo,mode,key,Valence,time_signature,popularity,Stream
0,En Iniya Pon Nilave,K J Yesudas,/artist/k-j-yesudas,04:18,Tamil,04-04-2002,0.80,0.849,0.467,0.170,-3.264,0.0200,162.040,1,0,0.0600,4,46,7160839
1,Andhi Mazhai Pozhigirathu,S. Janaki|S. P. Balasubrahmanyam|T.V. Gopalakr...,/artist/s-janaki|/artist/s-p-balasubrahamanyam...,04:36,Tamil,01-03-2023,0.10,0.360,0.039,0.180,-4.747,0.0677,151.990,1,5,0.0688,4,53,4329874
2,Madai Thiranthu,S. P. Balasubrahmanyam,/artist/s-p-balasubrahamanyam,04:21,Tamil,06-12-2013,0.82,0.565,0.618,0.292,-8.403,0.0100,128.026,0,5,0.0834,4,47,7299039
3,Ilamai Ennum Poonkaatru,S. P. Balasubrahmanyam,/artist/s-p-balasubrahamanyam,04:08,Tamil,07-07-2002,0.02,0.200,0.378,0.670,-9.441,0.0210,169.464,1,5,0.0200,4,51,8531979
4,Ithu Oru Ponmalai,S. P. Balasubrahmanyam,/artist/s-p-balasubrahamanyam,04:20,Tamil,04-03-2020,0.29,0.663,0.014,0.765,-12.583,0.0950,145.046,1,6,0.0190,4,77,4102936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4672,Pottane Oru Polu - Dialogues,T.M. Soundararajan,/artist/tm-soundararajan,03:02,Tamil,01-12-2011,0.39,0.714,0.664,0.610,-8.346,0.0800,111.791,1,1,0.0752,4,49,2465126
4673,Manmatha Oodangale,S. P. Balasubrahmanyam|S. Janaki,/artist/s-p-balasubrahamanyam|/artist/s-janaki,04:15,Tamil,09-03-2010,0.68,0.100,0.859,0.800,-5.642,0.0679,120.078,0,11,0.0837,4,32,8466540
4674,Angalamma,P Suhseela|Malaysia Vasudevan,/artist/p-suhseela|/artist/malaysia-vasudevan,05:29,Tamil,01-06-2004,0.96,0.670,0.438,0.505,-5.733,0.0793,140.042,1,10,0.0102,4,72,3917101
4675,Aalam Padaiththavane,Nellai S.M.Abul Barakath,/artist/nellai-smabul-barakath,07:50,Tamil,12-08-2002,0.91,0.680,0.690,0.200,-7.410,0.0964,159.806,1,5,0.0400,4,53,6000742
4676,Nadakattum Raja,S. P. Balasubrahmanyam,/artist/s-p-balasubrahamanyam,04:25,Tamil,04-12-2016,0.22,0.049,0.139,0.016,-9.530,0.0863,110.005,0,11,0.0455,4,96,8620930

In [8]:
d.columns

Index(['song_name', 'singer', 'singer_id', 'duration', 'language',
       'released_date', 'danceability', 'acousticness', 'energy', 'liveness',
       'loudness', 'speechiness', 'tempo', 'mode', 'key', 'Valence',
       'time_signature', 'popularity', 'Stream'],
      dtype='object')

In [20]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4677 entries, 0 to 4676
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   song_name       4677 non-null   object
 1   singer          4677 non-null   object
 2   singer_id       4677 non-null   object
 3   duration        4677 non-null   object
 4   language        4677 non-null   object
 5   released_date   4677 non-null   object
 6   danceability    4677 non-null   float64
 7   acousticness    4677 non-null   float64
 8   energy          4677 non-null   float64
 9   liveness        4677 non-null   float64
 10  loudness        4677 non-null   float64
 11  speechiness     4677 non-null   float64
 12  tempo           4677 non-null   float64
 13  mode            4677 non-null   int64
 14  key             4677 non-null   int64
 15  Valence         4677 non-null   float64
 16  time_signature  4677 non-null   int64
 17  popularity      4677 non-null   int64
 18  Stream          4677 non-null   int64
dtypes: float64(8), int64(5), object(6)
memory usage: 694.4+ KB

In [27]:
#feature engineering
x=d[["danceability","energy","tempo","loudness","Valence"]]
x

      danceability  energy    tempo  loudness  Valence
0             0.80   0.467  162.040    -3.264   0.0600
1             0.10   0.039  151.990    -4.747   0.0688
2             0.82   0.618  128.026    -8.403   0.0834
3             0.02   0.378  169.464    -9.441   0.0200
4             0.29   0.014  145.046   -12.583   0.0190
...            ...     ...      ...       ...      ...
4672          0.39   0.664  111.791    -8.346   0.0752
4673          0.68   0.859  120.078    -5.642   0.0837
4674          0.96   0.438  140.042    -5.733   0.0102
4675          0.91   0.690  159.806    -7.410   0.0400
4676          0.22   0.139  110.005    -9.530   0.0455

[4677 rows x 5 columns]

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
ss=StandardScaler()
ss

StandardScaler()

In [30]:
x=ss.fit_transform(x)
x

array([[ 1.03137762, -0.11425995,  0.32384745,  1.35638702,  0.35573566],
       [-1.39786806, -1.60449986, -0.05048221,  0.929722  ,  0.66034681],
       [ 1.10078464,  0.41150227, -0.94306288, -0.12212379,  1.16572439],
       ...,
       [ 1.58663378, -0.21523415, -0.49550616,  0.64604586, -1.36808651],
       [ 1.41311623,  0.66219683,  0.24063825,  0.16356627, -0.3365624 ],
       [-0.98142594, -1.25631297, -1.61428624, -0.44636619, -0.14618043]],
      shape=(4677, 5))

In [31]:
from sklearn.neighbors import NearestNeighbors

In [32]:
model=NearestNeighbors(n_neighbors=6,metric="euclidean")
model.fit(x)

NearestNeighbors(metric='euclidean', n_neighbors=6)

In [33]:
#d["singer"].unique()

In [34]:
x=["danceability","energy","tempo","loudness","Valence"]
def rec(song):
    x_index=d[d["song_name"]==song].index[0]
    query_point=d.loc[[x_index],x].values
    distance,indices=model.kneighbors(query_point)
    return d.iloc[indices[0]]["song_name"]
#3.test it
print(rec("Andhi Mazhai Pozhigirathu"))

4205             Vasandhamum Neeye
3704                    Swara Raga
4529                       Annamma
3300             Idhuthaan Ulagama
1844                      Kangalal
1615    Ennai Padavaithavan Oruvan
Name: song_name, dtype: object